version: '3.8'

volumes:
  db_data:

services:
  facebook-agent:
    build: .
    container_name: facebook_automation_agent
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./app:/usr/src/app/app
      - db_data:/usr/src/app
    ports:
      - "8000:8000"
    command: sh -c "alembic upgrade head && python app/main.py"