"""Add is_active_for_engagement to Post model

Revision ID: 04bc407ad7e8
Revises: 2be1bccab18b
Create Date: 2025-09-26 10:44:00.808300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04bc407ad7e8'
down_revision: Union[str, Sequence[str], None] = '2be1bccab18b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('is_active_for_engagement', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'is_active_for_engagement')
    # ### end Alembic commands ###
